name: Continuous Integration

on:
  pull_request:
    branches: [ master ]
  
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Flask REST API dependencies
        working-directory: ./api
        run: pip install -r requirements.txt
      
      - name: Install NLP Model dependencies
        working-directory: ./api/model
        run: pip install -r requirements.txt
      
      - name: Run backend tests
        working-directory: ./api/tests
        run: pytest -v
  
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install Node.js dependencies
        run: npm install
      
      - name: Run frontend tests
        run: npm run test